name: Build PRF Multas AML

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Baixar arquivos AML
        run: |
          git clone --depth 1 https://github.com/RusJJ/AndroidModLoader.git aml-temp
          mkdir -p include
          cp -r aml-temp/mod include/

      - name: Instalar Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Compilar mod AML
        run: |
          ndk-build \
            NDK_PROJECT_PATH=. \
            APP_BUILD_SCRIPT=./Android.mk \
            NDK_APPLICATION_MK=./Application.mk

      - name: Salvar arquivo compilado
        uses: actions/upload-artifact@v4
        with:
          name: PRFMultas-AML
          path: libs/armeabi-v7a/libPRFMultas.so
